Controllers/ClothesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MesDoigtsDeFees.Data;
using MesDoigtsDeFees.Models;

namespace MesDoigtsDeFees.Controllers
{
    public class ClothesController : Controller
    {
        private readonly MyDBContext _context;

        public ClothesController(MyDBContext context)
        {
            _context = context;
        }

        // GET: Clothes
        public async Task<IActionResult> Index(string selectedSize = "Alle")
        {



            List<ListItem> list = new List<ListItem>()
    {
        new ListItem() { Text = "XS", Value = "XS" },
        new ListItem() { Text = "S", Value = "S" },
        new ListItem() { Text = "M", Value = "M" },
        new ListItem() { Text = "L", Value = "L" },
        new ListItem() { Text = "XL", Value = "XL" },
    };

            ClothesIndexViewModel viewModel = new ClothesIndexViewModel();
            viewModel.SelectedSize = selectedSize;
            viewModel.SizeList = new SelectList(list, "Value", "Text", selectedSize);

            if (selectedSize == "Alle")
            {
                viewModel.Clothes = await _context.Clothes
                    .OrderBy(g => g.Name)
                    .Where(c => c.Ended == DateTime.MaxValue)
                    .ToListAsync();
                return View(viewModel);
            }
            else
            {
                ClothesIndexViewModel viewModel2 = new ClothesIndexViewModel
                {
                    SelectedSize = selectedSize,
                    Clothes = await _context.Clothes
                            .Where(c => selectedSize == "" || c.Size == selectedSize && c.Ended == DateTime.MaxValue)
                            .OrderBy(c => c.Name)
                            .ToListAsync()
                };

                return View(viewModel2);
            }
            
        }

        // GET: Clothes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Clothes == null)
            {
                return NotFound();
            }

            var clothes = await _context.Clothes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clothes == null)
            {
                return NotFound();
            }

            return View(clothes);
        }

        // GET: Clothes/Create
        public IActionResult Create()
        {
            ViewBag.SizeList = new List<string> { "XS", "S", "M", "L", "XL" };

            return View();
        }

        // POST: Clothes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Size,Started,Ended")] Clothes clothes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clothes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clothes);
        }

        

        // GET: Clothes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clothes == null)
            {
                return NotFound();
            }

            var clothes = await _context.Clothes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clothes == null)
            {
                return NotFound();
            }

            return View(clothes);
        }

        // POST: Clothes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clothes == null)
            {
                return Problem("Entity set 'MesDoigtsDeFeesContext.Clothes'  is null.");
            }
            var clothes = await _context.Clothes.FindAsync(id);
            if (clothes != null)
            {
                clothes.Ended = DateTime.Now;
                _context.Clothes.Update(clothes);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClothesExists(int id)
        {
          return (_context.Clothes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MesDoigtsDeFees.Data;
using MesDoigtsDeFees.Models;
using System.Runtime.CompilerServices;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MesDoigtsDeFees.Controllers
{
    public class GroupsController : Controller
    {
        private readonly MyDBContext _context;

        public GroupsController(MyDBContext context)
        {
            _context = context;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            return _context.Groups != null ?
                          View(await _context.Groups
                          .Where(g => g.Ended == DateTime.MaxValue)
                          .ToListAsync()) :
                          Problem("Entity set 'MesDoigtsDeFeesContext.Group'  is null.");
        }



        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Groups == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            ViewBag.CategorieList = new List<string> { "Dag", "Avond" };

            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Categorie,Started,Ended")] Group @group)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }

       

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Groups == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Groups == null)
            {
                return Problem("Entity set 'MesDoigtsDeFeesContext.Group'  is null.");
            }
            var @group = await _context.Groups.FindAsync(id);
            if (@group != null)
            {
                group.Ended = DateTime.Now;
                _context.Groups.Update(@group);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GroupExists(int id)
        {
          return (_context.Groups?.Any(e => e.Id == id)).GetValueOrDefault();
        }


    }
}

Controllers/TrajectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MesDoigtsDeFees.Data;
using MesDoigtsDeFees.Models;

namespace MesDoigtsDeFees.Controllers
{
    public class TrajectsController : Controller
    {
        private readonly MyDBContext _context;

        public TrajectsController(MyDBContext context)
        {
            _context = context;
        }

        // GET: Trajects
        public async Task<IActionResult> Index()
        {
              return _context.Richtings != null ? 
                          View(await _context.Richtings
                          .Where(t => t.Ended == DateTime.MaxValue)
                          .ToListAsync()) :
                          Problem("Entity set 'MesDoigtsDeFeesContext.Traject'  is null.");
        }

        // GET: Trajects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Richtings == null)
            {
                return NotFound();
            }

            var traject = await _context.Richtings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (traject == null)
            {
                return NotFound();
            }

            return View(traject);
        }

        // GET: Trajects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trajects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Started,Ended")] Richting traject)
        {
            if (ModelState.IsValid)
            {
                _context.Add(traject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(traject);
        }

       

        // GET: Trajects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Richtings == null)
            {
                return NotFound();
            }

            var traject = await _context.Richtings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (traject == null)
            {
                return NotFound();
            }

            return View(traject);
        }

        // POST: Trajects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Richtings == null)
            {
                return Problem("Entity set 'MesDoigtsDeFeesContext.Traject'  is null.");
            }
            var traject = await _context.Richtings.FindAsync(id);
            if (traject != null)
            {
                traject.Ended = DateTime.Now;
                _context.Richtings.Update(traject);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrajectExists(int id)
        {
          return (_context.Richtings?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/UsersController.cs
using MesDoigtsDeFees.Areas.Identity.Data;
using MesDoigtsDeFees.Data;
using MesDoigtsDeFees.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace MesDoigtsDeFees.Controllers
{
    [Authorize(Roles = "SystemAdministrator")]
    public class UsersController : Controller
    {
        private readonly MyDBContext _context;
        public UsersController(MyDBContext context)
        {



            _context = context;
        }
        public IActionResult Index(string userName, string firstName, string lastName, string email)
        {
            List<UserIndexViewModel> vmUsers = new List<UserIndexViewModel>();
            List<MesDoigtsDeFeesUser> users = _context.Users
                                            .Where(u => u.UserName != "Dummy"
                                                    && (u.UserName.Contains(userName) || string.IsNullOrEmpty(userName))
                                                    && (u.FirstName.Contains(firstName) || string.IsNullOrEmpty(firstName))
                                                    && (u.LastName.Contains(lastName) || string.IsNullOrEmpty(lastName))
                                                    && (u.Email.Contains(email) || string.IsNullOrEmpty(email))
                                                   )
                                            .ToList();

            foreach (MesDoigtsDeFeesUser user in users)
            {
                vmUsers.Add(new UserIndexViewModel
                {
                    Blocked = !user.LockoutEnabled,
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    UserName = user.UserName,
                    Roles = (from userRole in _context.UserRoles
                             where userRole.UserId == user.Id
                             orderby userRole.RoleId
                             select userRole.RoleId).ToList()
                });
            }
            ViewData["userName"] = userName;
            ViewData["firstName"] = firstName;
            ViewData["lastName"] = lastName;
            ViewData["email"] = email;
            return View(vmUsers);
        }

        public IActionResult UnBlock(string userName)
        {
            MesDoigtsDeFeesUser user = _context.Users.FirstOrDefault(u => u.UserName == userName);
            user.LockoutEnabled = true;
            _context.Update(user);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Block(string userName)
        {
            MesDoigtsDeFeesUser user = _context.Users.FirstOrDefault(u => u.UserName == userName);
            user.LockoutEnabled = false;
            _context.Update(user);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Roles(string userName)
        {
            MesDoigtsDeFeesUser user = _context.Users.FirstOrDefault(u => u.UserName == userName);

            try
            {
                UserRolesViewModel roleViewModel = new UserRolesViewModel
                {
                    UserName = userName,
                    Roles = (from userRole in _context.UserRoles
                             where userRole.UserId == user.Id
                             orderby userRole.RoleId
                             select userRole.RoleId).ToList()
                };

                ViewData["AllRoles"] = new MultiSelectList(_context.Roles.OrderBy(r => r.Name), "Id", "Name", roleViewModel.Roles);

                return View(roleViewModel);
            }
            catch (Exception ex)
            {

                var errorViewModel = new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    // Voeg specifieke foutinformatie toe aan het ErrorViewModel
                    ErrorMessage = ex.Message
                };

                // Stuur het foutenmodel naar de weergave voor foutafhandeling
                return View("Error", errorViewModel);
            }
        }

        [HttpPost]
        public IActionResult Roles([Bind("UserName, Roles")] UserRolesViewModel _model)
        {
            MesDoigtsDeFeesUser user = _context.Users.FirstOrDefault(u => u.UserName == _model.UserName);

            // Bestaande rollen ophalen
            List<IdentityUserRole<string>> roles = _context.UserRoles.Where(ur => ur.UserId == user.Id).ToList();
            foreach (IdentityUserRole<string> role in roles)
                _context.Remove(role);

            // Nieuwe rollen toekennen
            if (_model.Roles != null)
                foreach (string roleId in _model.Roles)
                    _context.UserRoles.Add(new IdentityUserRole<string> { RoleId = roleId, UserId = user.Id });

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_LanguagePartial.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.AspNetCore.Mvc.Localization;

@{
    string languageId = "nl";
    string cookieCulture = Context.Request.Cookies[CookieRequestCultureProvider.DefaultCookieName];
    if (cookieCulture != null)
    {
        languageId = cookieCulture.Substring(2, 2);
    }
    string LanguageName = Language.LanguagesById[languageId].Name;

    var thisPage = string.IsNullOrEmpty(Context.Request.Path) ? "~/index.html" : $"~{Context.Request.Path.Value}";
}

<ul class="navbar-nav">
    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown" data-bs-toggle="dropdown">@LanguageName</a>
        <ul class="dropdown-menu">
            @foreach (Language language in Language.Languages)
                if (language.Id != languageId && language.IsSystemLanguage)
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area=""
                           asp-controller="Languages"
                           asp-action="ChangeLanguage"
                           asp-route-id="@language.Id"
                           asp-route-returnUrl="@thisPage">
                            @language.Name
                        </a>
                    </li>
                }
        </ul>
    </li>
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MesDoigtsDeFees</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MesDoigtsDeFees.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MesDoigtsDeFees</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if (User.Identity.IsAuthenticated)
                        {


                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown">@_localizer["Onderwijs"]</a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="Index">@_localizer["Groepen"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Lessons" asp-action="Index">@_localizer["Lessen"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Trajects" asp-action="Index">@_localizer["Richtingen"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="LessonRichtings" asp-action="Index">@_localizer["Trajecten"]</a>
                                    </li>

                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clothes" asp-action="Index">@_localizer["Kledingstukken"]</a>
                            </li>
                            @if (User.IsInRole("SystemAdministrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">@_localizer["Gebruikers"]</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Languages" asp-action="Index">@_localizer["Talen"]</a>
                                </li>
                                <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown">@_localizer["Systeem"]</a>
                                <ul class="dropdown-menu">
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Parameters" asp-action="Index">@_localizer["Parameters"]</a>
                                        </li>
                                </ul>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@_localizer["Privacy"]</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <partial name="_LanguagePartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MesDoigtsDeFees - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>