Models/Lesson.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MesDoigtsDeFees.Models
{
    public class Lesson
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Veld is leeg")]
        [Display(Name = "Naam")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Veld is leeg")]
        [Display(Name = "Beschrijving")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Veld is leeg")]
        [Display(Name = "Type")]
        public string Type { get; set; }
        public List<string> TypeList { get; } = new List<string> { "Theorie", "Praktijk" };
        [ForeignKey("Group")]
        public int GroupId { get; set; }
        [Display(Name = "Groep")]
        public Group? Group { get; set; }
        //public List<Group>? Groups { get; set; }
        //public List<Traject>? Trajects { get; set; }
        [Display(Name = "Les aangemaakt")]
        public DateTime Started { get; set; } = DateTime.Now;
        [Display(Name = "Les gestopt")]
        public DateTime Ended { get; set; } = DateTime.MaxValue;

        [ForeignKey("Richting")]
        public int? RichtingId { get; set; }

        [Display(Name = "Richting")]
        public Richting? Richting { get; set; } 
        public string? RichtingName { get; set; }



    }

    public class LessonIndexViewModel
    {
        public List<Lesson> Lessons { get; set; }
        public string SelectedType { get; set; } = "Alle";
        public SelectList TypeList { get; set; }

        
        public LessonIndexViewModel()
        {
            TypeList = new SelectList(new List<string> { "Theorie", "Praktijk" });
        }
    }



   
}

Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MesDoigtsDeFees.Data;
using MesDoigtsDeFees.Models;
using Microsoft.Extensions.Localization;

namespace MesDoigtsDeFees.Controllers
{
    public class LessonsController : Controller
    {
        private readonly MyDBContext _context;
        private readonly IStringLocalizer<LessonsController> _localizer;



        public LessonsController(MyDBContext context, IStringLocalizer<LessonsController> localizer)
        {
            _context = context;
            _localizer = localizer;

        }

        // GET: Lessons


        // GET: Lessons/Details/5
        public async Task<IActionResult> Index(string selectedType = "Alle")
        {

            List<ListItem> groupList = _context.Groups
                    .Select(g => new ListItem() { Text = g.Name, Value = g.Name })
                    .ToList();
            List<ListItem> list = new List<ListItem>()
        {
            new ListItem() { Text = _localizer["Theorie"], Value = _localizer["Theorie"] },
            new ListItem() { Text = _localizer["Praktijk"], Value = _localizer["Praktijk"] },
        };

            LessonIndexViewModel viewModel = new LessonIndexViewModel();
            viewModel.SelectedType = selectedType;
            viewModel.TypeList = new SelectList(list, "Value", "Text", selectedType);

            if (selectedType == "Alle")
            {
                viewModel.Lessons = await _context.Lessons
                    .OrderBy(l => l.Name)
                    .Include(l => l.Group)
                    .Where(l => l.Ended == DateTime.MaxValue)
                    .ToListAsync();
                return View(viewModel);
            }
            else
            {
                LessonIndexViewModel viewModel2 = new LessonIndexViewModel
                {
                    SelectedType = selectedType,

                    Lessons = await _context.Lessons
                        .Where(l => selectedType == "" || l.Type == selectedType)
                        .Include(l => l.Group)
                        .Where(l => l.Ended == DateTime.MaxValue)
                        .OrderBy(l => l.Name)
                        .ToListAsync()

                };

                return View(viewModel2);
            }

            
        }

    

    // GET: Lessons/Create
    public IActionResult Create()
        {
            ViewBag.TypeList = new List<string> { _localizer["Theorie"], _localizer["Praktijk"] };
            ViewBag.GroupList = new SelectList(_context.Groups, "Id", "Name");


            return View();
        }

        // POST: Lessons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Type,GroupId")] Lesson lesson)
        {
            if (ModelState.IsValid)
            {
                // Controleer of de opgegeven RichtingId geldig is
                if (lesson.RichtingId.HasValue && !_context.Richtings.Any(r => r.Id == lesson.RichtingId))
                {
                    ModelState.AddModelError("RichtingId", "Ongeldige RichtingId");
                    return View(lesson);
                }
                _context.Add(lesson);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Als er validatiefouten zijn, stel de ViewBag opnieuw in met de juiste waarden
            ViewBag.TypeList = new List<string> {  _localizer["Theorie"],_localizer["Praktijk"] };
            ViewBag.GroupList = new SelectList(_context.Groups, "Id", "Name", lesson.GroupId);

            return View(lesson);
        }


        

        // GET: Lessons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Lessons == null)
            {
                return NotFound();
            }

            var lesson = await _context.Lessons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lesson == null)
            {
                return NotFound();
            }

            return View(lesson);
        }

        // POST: Lessons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Lessons == null)
            {
                return Problem("Entity set 'MesDoigtsDeFeesContext.Lesson'  is null.");
            }
            var lesson = await _context.Lessons.FindAsync(id);
            if (lesson != null)
            {
                lesson.Ended = DateTime.Now;
                _context.Lessons.Update(lesson);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LessonExists(int id)
        {
          return (_context.Lessons?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Lessons/Create.cshtml
@model MesDoigtsDeFees.Models.Lesson
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
@{
    ViewData["Title"] = "Create";
}

<h1>@_localizer["Maak een nieuwe les aan"]</h1>

<h4>@_localizer["Les"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" asp-items="@(new SelectList(ViewBag.TypeList))" class="form-control">
                    <option value="">@_localizer["Selecteer een type"]</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="GroupId" class="control-label">Group</label>
                <select asp-for="GroupId" asp-items="@(ViewBag.GroupList)" class="form-control">
                    <option value="">@_localizer["Selecteer een groep"]</option>
                </select>
                <span asp-validation-for="GroupId" class="text-danger"></span>
            </div>






            <div class="form-group">
                <input type="submit" value=@_localizer["Aanmaken"] class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@_localizer["Terug naar lijst"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Lessons/Delete.cshtml
@model MesDoigtsDeFees.Models.Lesson

@{
    ViewData["Title"] = "Delete";
}

<h1>Les verwijderen</h1>

<h3>Ben je zeker dat je dit wil verwijderen?</h3>
<div>
    <h4>Lesson</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index">Terug naar lijst</a>
    </form>
</div>

Views/Lessons/Details.cshtml
@model MesDoigtsDeFees.Models.Lesson

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Les</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Lessons/Index.cshtml
@model LessonIndexViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer

@{
    ViewData["Title"] = "Index";
}

<h1>@_localizer["Lessen"]</h1>

@if(User.IsInRole("SystemAdministrator"))
{
    <p>
        <a asp-action="Create">@_localizer["Maak een nieuwe les aan"]</a>
    </p>
}


<form asp-controller="Lessons" asp-action="Index" method="get">
    <h4>
        <select asp-for="SelectedType" asp-items="Model.TypeList" onchange="this.form.submit()">
            <option value="Alle">@_localizer["Alle Lessen"]</option>

        </select>
        </h4>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @_localizer["Naam"]
            </th>
            <th>
                @_localizer["Beschrijving"]
            </th>
            <th>
                @_localizer["Type"]
            </th>
            <th>
                @_localizer["Groep"]
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Lessons) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
             <td>
                    @Html.DisplayFor(modelItem => item.Group.Name)
             </td>
            <td>

                    @if (User.IsInRole("SystemAdministrator"))
                    {
                        <a asp-action="Details" asp-route-id="@item.Id">@_localizer["Details"]</a>
                        <a asp-action="Delete" asp-route-id="@item.Id">@_localizer["Verwijderen"]</a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>